<?php
/**
 * Barangay data for Cebu cities
 * Returns an array of barangays organized by city
 */

function getCebuBarangays() {
    return array(
        'CEBU CITY' => array(
            'Adlaon',
            'Agsungot',
            'Apas',
            'Babag',
            'Bacayan',
            'Banilad',
            'Basak Pardo',
            'Basak San Nicolas',
            'Binaliw',
            'Bonbon',
            'Budlaan',
            'Buhisan',
            'Bulacao',
            'Buot-Taup',
            'Busay',
            'Calamba',
            'Cambinocot',
            'Capitol Site',
            'Carreta',
            'Central',
            'Cogon Pardo',
            'Cogon Ramos',
            'Day-as',
            'Duljo Fatima',
            'Ermita',
            'Guadalupe',
            'Guba',
            'Hippodromo',
            'Inayawan',
            'Kalubihan',
            'Kalunasan',
            'Kamagayan',
            'Kamputhaw',
            'Kasambagan',
            'Kinasang-an Pardo',
            'Labangon',
            'Lahug',
            'Lorega San Miguel',
            'Lusaran',
            'Luz',
            'Mabini',
            'Mabolo',
            'Malubog',
            'Mambaling',
            'Pahina Central',
            'Pahina San Nicolas',
            'Pamutan',
            'Pardo',
            'Pari-an',
            'Paril',
            'Pasil',
            'Pit-os',
            'Poblacion Pardo',
            'Pulangbato',
            'Pung-ol Sibugay',
            'Punta Princesa',
            'Quiot',
            'Sambag I',
            'Sambag II',
            'San Antonio',
            'San Jose',
            'San Nicolas Proper',
            'San Roque',
            'Santa Cruz',
            'Sapangdaku',
            'Sawang Calero',
            'Sinsin',
            'Sirao',
            'Suba',
            'Sudlon I',
            'Sudlon II',
            'T. Padilla',
            'Tabunan',
            'Tagbao',
            'Talamban',
            'Taptap',
            'Tejero',
            'Tinago',
            'Tisa',
            'Toong',
            'Zapatera'
        ),
        'MANDAUE CITY' => array(
            'Alang-alang',
            'Bakilid',
            'Banilad',
            'Basak',
            'Cabancalan',
            'Cambaro',
            'Canduman',
            'Casili',
            'Casuntingan',
            'Centro',
            'Cubacub',
            'Guizo',
            'Ibabao-Estancia',
            'Jagobiao',
            'Labogon',
            'Looc',
            'Maguikay',
            'Mantuyong',
            'Opao',
            'Pagsabungan',
            'Pakna-an',
            'Poblacion',
            'Subangdaku',
            'Tabok',
            'Tawason',
            'Tingub',
            'Tipolo',
            'Umapad'
        ),
        'LAPU-LAPU CITY' => array(
            'Agus',
            'Babag',
            'Bankal',
            'Baring',
            'Basak',
            'Buaya',
            'Calawisan',
            'Canjulao',
            'Caubian',
            'Cawhagan',
            'Caw-oy',
            'Gun-ob',
            'Ibo',
            'Looc',
            'Mactan',
            'Maribago',
            'Marigondon',
            'Pajac',
            'Pajo',
            'Pangan-an',
            'Poblacion',
            'Punta Engaño',
            'Pusok',
            'Sabang',
            'San Vicente',
            'Santa Rosa',
            'Subabasbas',
            'Talima',
            'Tingo',
            'Tungasan'
        ),
        'TALISAY CITY' => array(
            'Biasong',
            'Bulacao',
            'Cadulawan',
            'Camp IV',
            'Cansojong',
            'Dumlog',
            'Jaclupan',
            'Lagtang',
            'Lawaan I',
            'Lawaan II',
            'Lawaan III',
            'Linao',
            'Maghaway',
            'Manipis',
            'Mohon',
            'Poblacion',
            'Pooc',
            'San Isidro',
            'San Roque',
            'Tabunoc',
            'Tangke',
            'Tapul'
        )
    );
}
?>
